version: '2'
services:
  mongodb:
    image: mongo:latest
    restart: always
    networks:
      n3:
        ipv4_address: 172.20.0.2
    ports:
      - 27017:27017
  frontend:
    build: ./frontend
    depends_on:
      - mongodb
    networks:
      n3:
        ipv4_address: 172.20.0.4
    ports:
      - 1104:1104
networks:
  n3:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
